package edu.sdccd.cisc191;

import edu.sdccd.cisc191.ciphers.Vigenere;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import static org.junit.jupiter.api.Assertions.assertEquals;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class VigenereCipherTest {
    private String inputText, key;
    @Test
    public void testBasicEncode() {
        inputText = "Please work, I'm begging you to work";
        key = "pLeAsE";
        assertEquals("Ewiaki lzvk, A'q qpkgarv jsu ls lzvk", Vigenere.encode(inputText,key));
    }

    @Test
    public void testBasicDecode() {
        inputText = "Ewiaki lzvk, A'q qpkgarv jsu ls lzvk";
        key = "pLeAsE";
        assertEquals("Please work, I'm begging you to work", Vigenere.decode(inputText,key));
    }

    @Test
    public void testCryptanlysis() {    //Encrypted with "CISC"
        inputText = "Jq kvwlwpva!\n" +
                "\n" +
                "Ognkgog bg Kpbwtomvkcbw Lcds! Yg psxg if gzkavkvy uguwuvmj rnifpgl, uqxmjkpo lqrquu vpsv yqdn oicg awm c uwdkf Rsxc lwxgtgrgz, okvp s vcalg qn ojcb s uqnlyczw yqzcrniug yqdn dm dkmm. Ljka au cv suavujtwfqwa, xwntq qptapg kgwtaw, ogifkpo qqw egtm wf vjm uqwzkg qv qqwz gyp aujglmng, eavj ikukofogvlu fcw cv bzg gvv qh msej ewgm. Qf qtlwt vw ttklyg vpw icx tgvewgp wf-ecuhwu, qf rgzkqp kdcuawu, vpw eqtdgim seezwfkbsvkwf dqijf tmiwkzwu hcdna wfnkvw eqcjuga lq jing kvkvtcuvqz dgf qfvgzsevqgpu eavj alwfmfvu iff dmlygmf uvcvgpbk. Kp bzku kgwtaw, yg eann iuequhnkaz vjqk vjzgwip hggz jgxqwyu ckkpo jgewjfgl ketmwpeikvu iff fqkewakkqv tqczvu. K eann xmdnqkj pmo oqlmnga gp Ucffcg fkiplu yqlj c kgttmkrqvvkpo Sppwmpemegpb. Hngikg wbankhw aqcj hgtdqy kdcuaecvmk vq uszkuabg twctvapi. Q zcxm kgvch c Fqkeqzv ugzngt bg ocsw equewpqucvqgp dmlygmf cnt gh wa wcuqwt, iml vq ql xki ljg Lauewjf nqfm qv ljg vsxkosvkwf ogvm. Rnmsug zwikalgt iff uml aqcj wumj fkahncg fcom lq awmt tmsn pieg uw A mpwo yjw qqw ijg. Og ghhqug jwmtu ijg qv ljg aqnnitwu bg dg wxhkkacn, jmv K eann bja vw jguxgpf bg Fkauqtl ojgvwxgz A'o cb ea fmkm.\n" +
                "\n" +
                "Ypg co Q? A'xg jwgp egtmqfi ca s uqnlyczw gpoapgmj ukvug 1999 cvv jcdw yqzcgf il vjzwg ucuegakhwt kvczlwra, lyq ewtg jgwipl qwb, spf wfg iwl $100O kv kgtqwu F nmpfqfi, uw xct. Q'ng ubmem ijqwvv TYADkpsk vq if gzbwtpid ukbw. (hqzegttq UFT, xqtuwtng Dcpomcim Ogcdwt dmxqtm ljcb) shvmj vjm dcub sescaukbaqp ngt dmlvgz oqts-dkhm tcnifeg, vgy vpsv K'u s hcbzgt wx vjzwg awmpiqfu. ULD yca sevcsnng sescatgl ta TEK ncal Hctd, yjw hckl gwv 3f hgt azctm! Vca bg fcg, A yqzc kp Rsxc ngt oqutq-awtxqugu, lsvc estgpgwuqfi, cvv okvapi. Xqvjwf ku ckgf ngt oiujkvw ngijpkvy cpl fcvcjcn tspicsig xjqemkukvy. Vjm lyq tspicsiga uqoumpkksvg dac umjkctabgl eguasig mpejifig. Ixvgz lyq lweclwu qn uqfqfi, K'dw fkauqxmjgf i hcuaaqp ngt vmsejqfi cvv ycvl vq oaxg jsem bg vjm kqhboctm uqoumpkbq vjzgwip lgckzkpo. A'xg lgpg i lqp wx Lcds fgdwnqxwt kvlgtdagya spf ngwpl ljcb uqntwig ojcfa ljgaw fcgk ctm dcesapi qf gzxwtkmfeg eavj kwtviap vwhkea kq awm'nn pwct uw goxzcuqrg vpgug bgrkkk cu bzga kgog.\n" +
                "\n" +
                "Ew jcdw oqvljng stepavgkl ngdwn ewvkpo htqrweva ojkkz K jwhg yqdn jmdr awm dwqdf awmt rwjvhwdkq, xjgrijg awm hqz kqhboctm oqtshnckw da ckkpo apfckvtg kvcvvctl lqqtk kp bzku kgwtaw uwkz cu IOU, Iql, cpl Ecxmf. Yjqdg vpw uqnlyczw kplmuvzq ku pmig, bzg nmsfgzk hqze c vqyjv sfkv kgoocfkvg. Twktv aqcj tgxmvcbaqp bztqcyj uwdkf, xgtvitng kgfg, iff eweowvaecbaqp. Vwvywjm yqlj qbzgta ojgvwxgz qqw ksp. Cblgpl dqeid ogmlwra, uqpnwtgvugu, ngnnwo vgkz lqcjpctk, cpl tnqok vq alca ch vq lsvg. Mngtg tki algr qf oa kstgmj ecuw vjzgwip s fgdwnqxwf tmdcvqgpupar. Ca qqw egtm eavj ggwt xwgta, kgnt qqwzkgndwu cvv mgmh cp mqg qcl hqz ojq ggw yifv vw oqts okvp. Ah awm ctm s ngivgt iff yifv vw dgcl s itwmr, dm ljg natub lq uqyp wx zgtm: Htqrwev Ojqwxk. Kp uq rtmnkqck enikuga, kvwlwpva oqtswf qv suuqypomfvu bgigbzgt bztqcyjqcl vjm uqwzkg cvv equewpqucvmv qp Lauewjf. Kv ljg kdcua Vkukgtf awtxmj, K jing rzglgkl itwmr epsvtwgou incktsdnm ojgzw aqc ucp @izwcvy-eu bsi om ojgvwxgz qqw vwgf uq hgmvdckc.\n" +
                "\n" +
                "Fgahkvm tgkvy c hcdna wfnkvw eniku, K alknt zqrm lq iml vq sfqy msej wx aqc. A yktd jqtv qhnaeg pgwta gp Fqkeqzv Htqvca ugtpqfiu il 8:15-9:30co. Q ognkgog dafgw jguxgpumk vq laueckukwfu ca ljgg zgnx sff i hgtagpct lqwkz vq wfnkvw eqcjuga. Ah awm jcdw c rzwhgzjgf vsog bzcv qk pqb gp vpw qhnaekid tqalgt, xdgcaw ngb eg mvgy. Awm ctm ognkgog bg ectd og \"Ifftmo.\" Kh ggw czw wpkgohwjvcjdg yqlj vpsv, vpwp \"Rzgh Jcspi\" qk hkvw, vqw.\n" +
                "\n" +
                "Hngikg iw ljtwmij bzg Ugdncjmu vw xcoqdkczabg ggwtawnh eavj pgy ym'dn qxwtcbw. Rnmsug kgpviuv om su uwgp ca qqw psxg ifa epsnnmfiga kq vpsv ym ucp egtm bgigbzgt bg ogml aqcj pgmvu.\n" +
                "\n" +
                "Vpw Oqlmnga hcim oknt tg vpw jquw rcow cu bzg ewmtum au qzycpqrgf ijqwvv vjil. Vjm xktal oqlmng eann jw uvqumkmv, cu ql yktd eqvlckv aphwjocbaqp ggw yqdn pmwf vpjqwozqwb ljg kgwtaw cpl oggsk yktd dg agtvmv kp lwuemffkvy qtlwt yqlj vpw cebaxg ewgm wf vqx.\n" +
                "\n" +
                "Tg ucjg vw kvcg sevqng kv Ucpdsu. Kn qqw ijg wvsdnm, hngikg nml og sfqy izgcl gh vqeg, qz vtqx ljg kgwtaw. K cu jgscatgl ta vpw uepgqn bg ftwh uvcvgpbk yjw stg qfcebaxg. Bzgtm au c eskvqfi nqkv qn kvwlwpva zcrxq vq bsmg ggwt ahqv.";

        assertEquals("Hi students!\n" +
                "\n" +
                "Welcome to Intermediate Java! We have an exciting semester planned, covering topics that will make you a solid Java developer, with a taste of what a software workplace will be like. This is an asynchronous, fully online course, meaning you work on the course on your own schedule, with assignments due at the end of each week. In order to bridge the gap between on-campus, in person classes, the college accreditation board requires fully online courses to have instructor led interactions with students and between students. In this course, we will accomplish this through peer reviews using recorded screencasts and discussion boards. I will publish new modules on Sunday nights with a corresponding Announcement. Please utilize your fellow classmates to maximize learning. I have setup a Discord server to make communication between all of us easier, get to it via the Discord link on the navigation menu. Please register and set your user display name to your real name so I know who you are. My office hours are on the syllabus to be official, but I will try to respond to Discord whenever I'm at my desk.\n" +
                "\n" +
                "Who am I? I've been working as a software engineer since 1999 and have worked at three successful startups, two were bought out, and one got $100M in series D funding, so far. I've stuck around RWSLinks to an external site. (formerly SDL, formerly Language Weaver before that) after the last acquisition for better work-life balance, now that I'm a father of three youngins. SDL was actually acquired by RWS last Fall, who paid out 3x per share! Day to day, I work in Java for micro-services, data warehousing, and mining. Python is used for machine learning and natural language processing. The two languages communicate via serialized message exchange. After two decades of coding, I've discovered a passion for teaching and want to give back to the software community through teaching. I've done a ton of Java developer interviews and found that college grads these days are lacking in experience with certain topics so you'll hear me emphasize those topics as they come.\n" +
                "\n" +
                "We have monthly architect level coding projects which I hope will help you build your portfolio, prepare you for software workplace by using industry standard tools in this course such as AWS, Git, and Maven. While the software industry is huge, the leaders form a tight knit community. Build your reputation through solid, portable code, and communication. Network with others whenever you can. Attend local meetups, conferences, follow tech journals, and blogs to stay up to date. Every big step in my career came through a developed relationship. As you work with your peers, sell yourselves and keep an eye out for who you want to work with. If you are a leader and want to lead a group, be the first to sign up here: Project Groups. In my previous classes, students worked on assignments together throughout the course and communicated on Discord. In the class Discord server, I have project group chatrooms available where you can @ahuang-cs tag me whenever you need my feedback.\n" +
                "\n" +
                "Despite being a fully online class, I still hope to get to know each of you. I will hold office hours on Discord Friday mornings at 8:15-9:30am. I welcome video responses to discussions as they help add a personal touch to online courses. If you have a preferred name that is not on the official roster, please let me know. You are welcome to call me \"Andrew.\" If you are uncomfortable with that, then \"Prof Huang\" is fine, too.\n" +
                "\n" +
                "Please go through the Syllabus to familiarize yourself with how we'll operate. Please contact me as soon as you have any challenges so that we can work together to meet your needs.\n" +
                "\n" +
                "The Modules page will be the home page as the course is organized around that. The first module will be stickied, as it will contain information you will need throughout the course and weeks will be sorted in descending order with the active week on top.\n" +
                "\n" +
                "Be sure to stay active in Canvas. If you are unable, please let me know ahead of time, or drop the course. I am required by the school to drop students who are inactive. There is a waiting list of students happy to take your spot."
        , Vigenere.decode(inputText, ""));
    }

    @Test
    public void testCryptanlysisAlt() { //Encrypted with "ANDREWHUANG"
        inputText = "Hv vkyzlhtf!\n" +
                "\n" +
                "Ceyffqa ai Iazeepvhehne Wgvn! Zv lwcy aa kxplkmjn mezksghi thhhnrj, cbyvveua tbvipv klwa qiyr mnnv ckb u sbriq Mrzw kyvrrochi, aeab a ggsgh fj sout n yoswnenl qoeqpydti spfl ok lvnv. Xdpm if gn nvpryoloauuf, ilphf inyonr ffynzy, mrgnvqx ckb qoeq oa wyi yvorfk oa bfyn vqn fihrglpa, dctu gsflxrilhtf jur dk xdl ynq uf rdtl slyk. Vt oegvv pv vrvjgr wyi chj brzwrhe sj-jumcas, vq ginzin prafvvw, poy cbrlrjv eyjleqotnwzsj iiaej rrtlmnlm fhrll repeuy cbarfhj xk ouvr onfwiyyair ykd vqkinhwtvunf zzxd znuqkngv rrz iytjkea vkyzlhtf. On gkzw yvorfk, wr zzph hwcbspyljl pocs gnrbxxl llyr ekvvhnw qzcnt xeprihak mcekeafrwpz unq jifflwopin ouaegj. M spfl cabyljl jlq mbjuyhj sj Zonqgy alxlpz qign a privazjoajiaj Rrjvonpkmrqk. Thlusr atvozda fiue leyofa ysusfsaghj xk tuxvsimh ciwyhiam. I udmi olnuc g Dvvtsnk meebee wf qwry cbsmhqzgwacoa hegzvij hfl bl uf hrwell, grz tb lk zeh nhr Jifffvz scnx un gkv rwccgnzibq dijb. Jlrgsr uvkeznee gnq vvx uvor hyee gzwlsuy agmr wf ckbl rrgl addi ov C kauw jkf ckb urr. Sy biwmyl bohxs nuv sj abe felydsyo ai br ufsltmws, vug O wvoc xnf no ekscreh pv Xifioeg nlauyvrx I'z dk qu kysx.\n" +
                "\n" +
                "Chb dd M? E'cy brkn jrioeua af g sbikawyy eamiahvv ophcr 1999 gnq krza dirxkd nw klnly shicrvjjqs mtnxthsj, xsv qeek bbxxlp vot, ntd bqv kka $100G ia yeelvw Z monqont, vf jwy. C'vr ythfb envonq XWFOzrgz no nt ekwvvjhf svze. (sriqayfy FJL, sriqayfy Ygntxrka Dyaikr ohwsnl nhnz) aswvv poy lnyt nfhyezctvun sri faanee coen-cmbl vaygnph, ess abag O'm n irxdll os zhehv ckbhgvts. FGC awz ucgaayop eyxoiekd ob IAO susg Layo, nlk wuiq uug 3a gin zbaek! Dnb ks zhs, I jurx le Nwcu fbx mvfis-ollvvief, grxw durrnohvzrc, hhd zonvqx. Tuaboa os hvvh bvl mnihvqv pahlnvtg nqu rwaornr lnqxywny peucrvjmjn. Nhr zwb orrcbugry cbpdyjpwagk vvd jinpulvfeq pvwohae rdcudeka. Hztrx tjr uiyhxef uf prumjn, C'vr jifffzayyd n vafvzsj mir gkapkzrc hhd jgng wf kecy bnik gr kla zifgcaeh tsitonvzy gkisqnb trgculek. E'cy dbte n wfr km Daig dryvpkwyr vttrummadm aaj fbxeh pout pulyhxi cyudf zhrvv hwfm aek lnfbmjn cn rdpruzijjy wvzh phixwph tbvipv js uvo'ly nenu di atjhnyimh klkzy tbvipv rw poyy pumr.\n" +
                "\n" +
                "Zv lwcy mbttuop enjbigkcg ovzas woqont sisflwtf chvfy M dvje joly kvpl fiu oaiyg psqy joezfbozs, lyypnxe lrl jky moszwnuv akyepygcr ep yophg vtdhvkvu znaajaeg ksksm ia zhvv tsqyme facu dj ESZ, Aig, gnq Przau. Qhvre gkv wkmnwnxe vquyoaly vy hhjv, xdl fenjeev wsnt u tvmhg nemp jimzanvwp. Fqpfd luue uvtqautvun gkisqnb sbriq, sfvphvlr ioqh, rrz jimzanvfrxevh. Nrzwbub aeab ogneev nlauyvrx ybx tej. Hntrtd yrteh tyegapf, ffrblleaief, ifphvq trih wrlvjhfs, ntd oofko ai sggy hs ks zhne. Rbeeb smc znec on zb tenlyr pgmr wyvkbah n jeihcsllx rrraglfroocp. Ny ybx nsnr qign ybxi talls, fkly bfynzyliks nqu oalj aa kyr rlx bvl wuu ybx neja no jurx zzxd. Pz yba aeh r pahxee gnq zrrp ai lrgd n jisqw, ve gne sliwp ai svmn hs yinl: Jrbpepw Xvkbjs. Vt ml siirpiuf ilnvjio, znuqkngv nsnryd bt afvzkjtyngy tbjvxdll tuxohjysqa nhr iohuji wux cbsmhqzgwayd bt Dvvtsnk. Cn gne porwo Kcspurq vvvrll, I ugvr sisflwt txohs tlwalobss nyrmhhvlr chruv ckb waa @ghhdek-yz nat se jkvracyr luu ahvh if zerjbnfb.\n" +
                "\n" +
                "Hazjigk brlek w molye oaozra jfafy, I fwzph oipr zo thk xk rhoj kapk fj uvo. I joly kfpz vzfvie urlvo vh Dvycbuu Jnpxal soeqzrcz ut 8:15-9:30ns. I jhcgkty vvjeb uvwlvhsry tb gzwybmsvunf dj xdls hrrp ngu e lllsbtay wfyyo no btlvqv gkblsry. Is bfy dhpe n vrrivvnlx nnse gkrx ez hog un gkv sbmccvgl erjxay, jlrgsr ovx il enbc. Ybx rva dylpumr wf gwsf mr \"Gnquva.\" Em soh grr xegktzoezaoov aeab tugt, gkvr \"Lyif Uaaaj\" zw bphe, guo.\n" +
                "\n" +
                "Coveol ao gnrbxxl poy Slrlnelw pv zazolvdimvl sohxsrow aeab hbc wr'oc slllagk. Pyhrwa jinggcg pv eo zioa gs lrl lwcy aae cudcpauaef yo gkrx sl waa coen ksclnhrx tb pvip fiue tergj.\n" +
                "\n" +
                "Xdl Goqalrv gecl qiyr br wyi dvge cggr dj xdl wohxsr lj snnunvfeq disqux tugt. Gkv jeymt zudhov aesf br ytvfbmak, us vz wvoc gkunavt iaifvihnibt ybx nmhs herj tuufycoiug zhr ffynzy aaj wrhbw spfl ok sbukiz ph drycrqumjn irqkr jlkl poy apziih niar in gup.\n" +
                "\n" +
                "Oh jynl no fzal dtxecy ia Iaayrw. Em soh grr xeexsy, pykafh cip ty kauw nkvez vz tvse, bu uvkw nhr iohuji. E hg rrwuvuvh xf nhr ycurfp pv xrbv sgxuijam wuu aeh zrwjniik. Tuhii ez u wnotvqx pezn os ythgvrpz bacvy gr kegl sohx scrk.";
        assertEquals("Hi students!\n" +
                        "\n" +
                        "Welcome to Intermediate Java! We have an exciting semester planned, covering topics that will make you a solid Java developer, with a taste of what a software workplace will be like. This is an asynchronous, fully online course, meaning you work on the course on your own schedule, with assignments due at the end of each week. In order to bridge the gap between on-campus, in person classes, the college accreditation board requires fully online courses to have instructor led interactions with students and between students. In this course, we will accomplish this through peer reviews using recorded screencasts and discussion boards. I will publish new modules on Sunday nights with a corresponding Announcement. Please utilize your fellow classmates to maximize learning. I have setup a Discord server to make communication between all of us easier, get to it via the Discord link on the navigation menu. Please register and set your user display name to your real name so I know who you are. My office hours are on the syllabus to be official, but I will try to respond to Discord whenever I'm at my desk.\n" +
                        "\n" +
                        "Who am I? I've been working as a software engineer since 1999 and have worked at three successful startups, two were bought out, and one got $100M in series D funding, so far. I've stuck around RWSLinks to an external site. (formerly SDL, formerly Language Weaver before that) after the last acquisition for better work-life balance, now that I'm a father of three youngins. SDL was actually acquired by RWS last Fall, who paid out 3x per share! Day to day, I work in Java for micro-services, data warehousing, and mining. Python is used for machine learning and natural language processing. The two languages communicate via serialized message exchange. After two decades of coding, I've discovered a passion for teaching and want to give back to the software community through teaching. I've done a ton of Java developer interviews and found that college grads these days are lacking in experience with certain topics so you'll hear me emphasize those topics as they come.\n" +
                        "\n" +
                        "We have monthly architect level coding projects which I hope will help you build your portfolio, prepare you for software workplace by using industry standard tools in this course such as AWS, Git, and Maven. While the software industry is huge, the leaders form a tight knit community. Build your reputation through solid, portable code, and communication. Network with others whenever you can. Attend local meetups, conferences, follow tech journals, and blogs to stay up to date. Every big step in my career came through a developed relationship. As you work with your peers, sell yourselves and keep an eye out for who you want to work with. If you are a leader and want to lead a group, be the first to sign up here: Project Groups. In my previous classes, students worked on assignments together throughout the course and communicated on Discord. In the class Discord server, I have project group chatrooms available where you can @ahuang-cs tag me whenever you need my feedback.\n" +
                        "\n" +
                        "Despite being a fully online class, I still hope to get to know each of you. I will hold office hours on Discord Friday mornings at 8:15-9:30am. I welcome video responses to discussions as they help add a personal touch to online courses. If you have a preferred name that is not on the official roster, please let me know. You are welcome to call me \"Andrew.\" If you are uncomfortable with that, then \"Prof Huang\" is fine, too.\n" +
                        "\n" +
                        "Please go through the Syllabus to familiarize yourself with how we'll operate. Please contact me as soon as you have any challenges so that we can work together to meet your needs.\n" +
                        "\n" +
                        "The Modules page will be the home page as the course is organized around that. The first module will be stickied, as it will contain information you will need throughout the course and weeks will be sorted in descending order with the active week on top.\n" +
                        "\n" +
                        "Be sure to stay active in Canvas. If you are unable, please let me know ahead of time, or drop the course. I am required by the school to drop students who are inactive. There is a waiting list of students happy to take your spot."
                , Vigenere.decode(inputText, ""));
    }
}